import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { Helmet } from 'react-helmet-async'
import { ArrowRight } from 'lucide-react'
import Logo from '../../components/Logo'
import { useI18n } from '../i18n'
import { signUp } from '../store'
import type { Region } from '../types'
import LocaleSwitcher from './LocaleSwitcher'

export default function AuthForm({ mode }: { mode: 'signup' | 'login' }) {
  const { t, isRTL, locale, setLocale } = useI18n()
  const isFranco = locale === 'fr-eg'
  const navigate = useNavigate()
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [region, setRegion] = useState<Region>('gulf')
  const isSignup = mode === 'signup'

  function submit(e: React.FormEvent) {
    e.preventDefault()
    signUp(name || email.split('@')[0] || 'Founder', email || 'demo@autoleadss.com', region)
    navigate(isSignup ? '/app/new' : '/app')
  }

  const title = isSignup
    ? (isRTL ? 'إنشاء حساب — AutoLeadss' : isFranco ? 'Emel account — AutoLeadss' : 'Sign up — AutoLeadss')
    : (isRTL ? 'تسجيل الدخول — AutoLeadss' : isFranco ? 'Log in — AutoLeadss' : 'Log in — AutoLeadss')
  const htmlLang = isRTL ? 'ar' : isFranco ? 'ar-Latn' : 'en'

  return (
    <div dir={isRTL ? 'rtl' : 'ltr'} className="grid min-h-screen lg:grid-cols-2">
      <Helmet defer={false}>
        <html lang={htmlLang} dir={isRTL ? 'rtl' : 'ltr'} />
        <title>{title}</title>
        <meta name="description" content={isSignup ? t.auth.signupSub : t.auth.loginSub} />
        <link rel="canonical" href={`https://autoleadss.com/${isSignup ? 'signup' : 'login'}`} />
      </Helmet>
      <div className="relative hidden overflow-hidden lg:flex" style={{ background: '#0A0A0B' }}>
        <div aria-hidden className="absolute inset-0 grid-bg-dark" style={{ maskImage: 'radial-gradient(ellipse at 40% 40%, black, transparent 75%)', WebkitMaskImage: 'radial-gradient(ellipse at 40% 40%, black, transparent 75%)' }} />
        <div aria-hidden className="absolute -top-20 opacity-50 blur-3xl" style={{ insetInlineStart: '-10%', width: '60%', height: '60%', background: 'radial-gradient(circle, rgba(255,92,42,0.35), transparent 65%)' }} />
        <div className="relative z-10 flex flex-col justify-between p-12">
          <Logo variant="dark" size={34} />
          <div>
            <h2 className="font-display font-bold text-white" style={{ fontSize: 'clamp(1.8rem, 3vw, 2.8rem)', letterSpacing: '-0.03em', lineHeight: 1.1 }}>
              {isRTL ? 'قمع مبيعات كامل — يولّده الذكاء الاصطناعي خلال دقائق.' : 'A complete sales funnel — generated by AI in minutes.'}
            </h2>
            <p className="mt-4 max-w-sm text-white/60">
              {isRTL ? 'صفحة هبوط، إعلانات، بوت واتساب، وسوشيال — بالعربي والإنجليزي.' : 'Landing page, ads, WhatsApp bot, and social — in Arabic and English.'}
            </p>
          </div>
          <div className="flex items-center gap-3 text-white/40 text-xs">
            <span className="h-1 w-1 rounded-full bg-accent" /> {isRTL ? 'مبني للخليج ومصر' : 'Built for the Gulf & Egypt'}
          </div>
        </div>
      </div>

      <div className="flex flex-col justify-center bg-background px-6 py-10 sm:px-12">
        <div className="mx-auto w-full max-w-sm">
          <div className="mb-8 flex items-center justify-between lg:hidden">
            <Logo size={30} />
          </div>
          <div className="mb-6">
            <LocaleSwitcher locale={locale} setLocale={setLocale} />
          </div>
          <h1 className="font-display text-3xl font-bold" style={{ letterSpacing: '-0.02em' }}>
            {isSignup ? t.auth.signupTitle : t.auth.loginTitle}
          </h1>
          <p className="mt-2 text-sm text-muted-fg">{isSignup ? t.auth.signupSub : t.auth.loginSub}</p>

          <form onSubmit={submit} className="mt-8 flex flex-col gap-4">
            {isSignup && (
              <Field label={t.auth.name}>
                <input value={name} onChange={(e) => setName(e.target.value)} className={inputClass} placeholder={isRTL ? 'اسمك' : 'Your name'} />
              </Field>
            )}
            <Field label={t.auth.email}>
              <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} className={inputClass} placeholder="you@company.com" dir="ltr" />
            </Field>
            {isSignup && (
              <Field label={t.auth.region}>
                <div className="grid grid-cols-2 gap-2">
                  {(['gulf', 'egypt'] as Region[]).map((r) => (
                    <button key={r} type="button" onClick={() => setRegion(r)} className={`rounded-lg border px-4 py-2.5 text-sm font-medium transition-colors ${region === r ? 'border-accent bg-accent/10 text-accent' : 'border-border text-muted-fg hover:border-accent/40'}`}>
                      {r === 'gulf' ? t.auth.gulf : t.auth.egypt}
                    </button>
                  ))}
                </div>
              </Field>
            )}
            <button type="submit" className="group mt-2 inline-flex items-center justify-center gap-2 rounded-full bg-accent py-3.5 text-sm font-medium text-white transition-all hover:-translate-y-0.5 hover:shadow-[0_12px_36px_-8px_rgba(255,92,42,0.6)]">
              {isSignup ? t.auth.createAccount : t.auth.login}
              <ArrowRight size={16} className={`transition-transform group-hover:translate-x-0.5 ${isRTL ? 'rotate-180' : ''}`} />
            </button>
          </form>

          <p className="mt-4 text-center text-xs text-muted-fg">{t.auth.demoNote}</p>

          <p className="mt-6 text-center text-sm text-muted-fg">
            {isSignup ? t.auth.haveAccount : t.auth.noAccount}{' '}
            <Link to={isSignup ? '/login' : '/signup'} className="font-medium text-accent hover:underline">
              {isSignup ? t.auth.login : t.auth.createAccount}
            </Link>
          </p>
          <p className="mt-3 text-center text-sm">
            <Link to="/" className="text-muted-fg hover:text-foreground">← {isRTL ? 'العودة للموقع' : 'Back to site'}</Link>
          </p>
        </div>
      </div>
    </div>
  )
}

const inputClass =
  'w-full rounded-lg border border-border bg-card px-4 py-3 text-sm text-foreground placeholder:text-muted-fg/60 focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/20 transition-all'

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="flex flex-col gap-1.5">
      <span className="text-xs font-medium text-muted-fg">{label}</span>
      {children}
    </label>
  )
}
