import { BarChart3, CreditCard, LayoutTemplate, QrCode } from 'lucide-react'
import { useLocale } from '../../i18n/LocaleProvider'

export default function Offer() {
  const { isRTL } = useLocale()
  const items = isRTL
    ? [['موقع بيع عربي وإنجليزي', 'صفحة باسم البراند تعرض الباقات وتبيعها بوضوح.', LayoutTemplate], ['باقات ودفع أونلاين', 'شهر أو ٣ أو ٦ أو ١٢ شهر على حساب التاجر المعتمد.', CreditCard], ['QR للعميل والموظف', 'بطاقة عضوية وماسح يسجل كل استخدام أو توصيل.', QrCode], ['لوحة تحكم للمالك', 'المشتركين والإيراد والتجديدات وأداء كل باقة.', BarChart3]] as const
    : [['Bilingual sales website', 'A branded Arabic and English page that presents and sells the packages.', LayoutTemplate], ['Packages and online payment', '1, 3, 6 or 12-month terms through the merchant’s approved account.', CreditCard], ['Customer pass + staff QR', 'A mobile membership pass and scanner that records every use or delivery.', QrCode], ['Simple owner dashboard', 'Members, revenue, renewals and package performance in one place.', BarChart3]] as const
  return <section id="offer" className="scroll-mt-28 bg-[#EFECE4] py-20 sm:py-24"><div className="content-width"><div className="max-w-2xl"><p className="eyebrow text-accent">{isRTL ? 'تستلم إيه' : 'What you get'}</p><h2 className="mt-3 font-display text-[clamp(2.1rem,4vw,3.5rem)] font-bold leading-[1.04] tracking-[-0.04em]">{isRTL ? 'منتج اشتراكات كامل باسم نشاطك.' : 'A complete membership product under your brand.'}</h2></div><div className="mt-10 grid gap-3 md:grid-cols-2">{items.map(([title, body, Icon], index) => <article key={title} className="grid grid-cols-[auto_1fr] gap-4 rounded-2xl bg-[#111214] p-5 text-white sm:p-6"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#fe8c58] text-[#111214]"><Icon size={20} /></span><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-white/35">0{index + 1}</p><h3 className="mt-1 font-display text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-white/62">{body}</p></div></article>)}</div><p className="mt-5 text-sm text-muted-fg">{isRTL ? 'التطبيق يُضاف على الموبايل كـ PWA. العميل يمتلك النسخة المسلّمة والبيانات.' : 'The product installs on phones as a PWA. The client owns the delivered software and data.'}</p></div></section>
}
