import { ArrowUpRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useLocale } from '../../i18n/LocaleProvider'

export default function Work() {
  const { locale, localePath, isRTL } = useLocale()
  const items = [
    { name: 'TUT', label: isRTL ? 'منتج حي' : 'Live product', body: isRTL ? 'دليل سفر لمصر بإجابات موثقة ومصادر واضحة.' : 'An Egypt travel product with sourced, verifiable answers.', image: '/work/tut.png', href: 'https://tutapp.co', external: true, frame: 'aspect-[19/10]' },
    { name: 'Lash Cartel', label: isRTL ? 'ديمو عميل' : 'Client demo', body: isRTL ? 'تجربة حجز راقية لاستوديو رموش في الزمالك.' : 'A premium booking experience for a Zamalek lash studio.', image: `/demos/lashes/${locale === 'ar' ? 'ar' : 'en'}-hero.png`, href: localePath('/demo/lashes'), external: false, frame: 'aspect-[20/9]' },
    { name: 'MBAI Group', label: isRTL ? 'موقع المجموعة' : 'Group website', body: isRTL ? 'واجهة تحريرية لمجموعة ذكاء اصطناعي ومنتجات في المنطقة.' : 'An editorial site for a regional AI and product group.', image: '/work/mbai.png', href: 'https://mbai-group.com', external: true, frame: 'aspect-[19/10]' },
  ]
  return <section id="work" className="scroll-mt-28 bg-[#0A0A0B] py-20 text-white sm:py-24"><div className="content-width"><div className="max-w-2xl"><p className="eyebrow text-[#fe8c58]">{isRTL ? 'أفضل شغلنا' : 'Selected work'}</p><h2 className="mt-3 font-display text-[clamp(2.1rem,4vw,3.5rem)] font-bold leading-[1.04] tracking-[-0.04em]">{isRTL ? 'شغل حقيقي. بدون حشو.' : 'Real work. No filler.'}</h2></div><div className="mt-10 grid gap-6 lg:grid-cols-12">{items.map((item, index) => { const cls = index === 0 ? 'lg:col-span-7' : index === 1 ? 'lg:col-span-5' : 'lg:col-span-12'; const content = <><div className={`overflow-hidden rounded-2xl border border-white/10 bg-[#111113] ${item.frame}`}><img src={item.image} alt={item.name} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.015]" /></div><div className="mt-4 flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#4ade80]">{item.label}</p><h3 className="mt-1 font-display text-2xl font-bold">{item.name}</h3><p className="mt-2 text-sm text-white/55">{item.body}</p></div><ArrowUpRight size={19} className="mt-1 shrink-0 text-[#fe8c58]" /></div></>; return item.external ? <a key={item.name} href={item.href} target="_blank" rel="noopener noreferrer" className={`group block ${cls}`}>{content}</a> : <Link key={item.name} to={item.href} className={`group block ${cls}`}>{content}</Link> })}</div></div></section>
}
