import { Helmet } from 'react-helmet-async'
import { ArrowUpRight, Coffee, Dog, QrCode, Scissors, Shirt, Waves } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { Link } from 'react-router-dom'
import Navigation from '../components/Navigation'
import Footer from '../components/Footer'
import ActionDock from '../components/ActionDock'
import { useLocale } from '../i18n/LocaleProvider'
import { SITE, waLink } from '../site'

type Blueprint = { icon: LucideIcon; category: [string, string]; package: [string, string]; allowance: [string, string]; rule: [string, string]; color: string }
const BLUEPRINTS: Blueprint[] = [
  { icon: Scissors, category: ['Barber', 'حلاقة'], package: ['Sharp Monthly', 'حلاقة الشهر'], allowance: ['2 cuts + 2 beard services', 'حلاقتان + خدمتا دقن'], rule: ['Maximum one visit weekly', 'حد أقصى زيارة أسبوعياً'], color: '#F2C078' },
  { icon: Waves, category: ['Car wash', 'غسيل سيارات'], package: ['Always Clean', 'دايماً نضيفة'], allowance: ['4 off-peak washes', '٤ غسلات في الأوقات الهادئة'], rule: ['One registered vehicle', 'لسيارة واحدة مسجلة'], color: '#67C7ED' },
  { icon: Shirt, category: ['Laundry', 'مغسلة'], package: ['Home 20', 'بيت ٢٠'], allowance: ['20 kg + 2 pickups', '٢٠ كجم + استلام مرتين'], rule: ['Allowance expires monthly', 'الرصيد ينتهي شهرياً'], color: '#A8D7C5' },
  { icon: Dog, category: ['Pet care', 'رعاية حيوانات'], package: ['Complete Care', 'عناية كاملة'], allowance: ['Dry + fresh food + grooming', 'طعام جاف وفريش + جروومينج'], rule: ['Delivery and grooming scheduled', 'التوصيل والجروومينج بالحجز'], color: '#F2A07D' },
  { icon: Coffee, category: ['Café', 'كافيه'], package: ['Daily 20', 'يومي ٢٠'], allowance: ['20 drinks each month', '٢٠ مشروباً كل شهر'], rule: ['Maximum one drink daily', 'حد أقصى مشروب يومياً'], color: '#D6B58C' },
]

export default function PackagesPage() {
  const { locale, isRTL, localePath } = useLocale()
  const ar = isRTL
  const title = ar ? 'قوالب وباقات العضويات | أوتوليدز' : 'Membership package templates | AutoLeadss'
  const description = ar ? 'قوالب عملية للحلاقة وغسيل السيارات والمغاسل ورعاية الحيوانات والكافيهات.' : 'Practical membership blueprints for barbers, car washes, laundries, pet care and cafés.'
  const steps = ar ? ['نحدد الشراء المتكرر', 'نضبط الرصيد وقواعد الاستخدام', 'نصمم صفحة البيع باسم النشاط', 'نربط الدفع وQR ولوحة المالك'] : ['Find the repeat purchase', 'Set allowance and usage rules', 'Design the branded sales page', 'Connect payment, QR and dashboard']
  return <div className="min-h-screen bg-[#F5F2EA] text-[#11110F]">
    <Helmet><html lang={locale} dir={ar ? 'rtl' : 'ltr'}/><title>{title}</title><meta name="description" content={description}/><link rel="canonical" href={`${SITE.origin}/${locale}/packages`}/></Helmet><Navigation/>
    <main>
      <section className="bg-[#0A0A0B] px-5 pb-24 pt-40 text-white md:px-8 md:pb-32"><div className="mx-auto max-w-[1200px]"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#FE8C58]">{ar ? 'مكتبة الباقات' : 'Package library'}</p><h1 className="mt-6 max-w-5xl font-display text-[clamp(3.3rem,8vw,7rem)] font-bold leading-[.9] tracking-[-.07em]">{ar ? 'نبدأ بقالب مجرّب. ثم نجعله ملكك.' : 'Start with a proven skeleton. Make it yours.'}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-white/58">{description} {ar ? 'الأسماء والأسعار هنا أمثلة؛ النسخة النهائية تبنى حول هامشك وتشغيلك.' : 'Names and prices are illustrative; the final version is built around your margin and operation.'}</p></div></section>
      <section className="px-5 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-[1200px]"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{BLUEPRINTS.map((item,index)=>{const Icon=item.icon; return <article key={item.category[0]} className="flex min-h-[350px] flex-col rounded-[28px] border border-black/10 bg-white p-6 shadow-[0_22px_55px_-45px_rgba(0,0,0,.35)]"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl" style={{background:item.color}}><Icon size={20}/></span><span className="font-mono text-[10px] text-black/30">0{index+1}</span></div><p className="mt-8 text-[10px] uppercase tracking-[.15em] text-black/38">{item.category[ar?1:0]}</p><h2 className="mt-2 font-display text-3xl font-bold">{item.package[ar?1:0]}</h2><p className="mt-4 text-sm leading-6 text-black/58">{item.allowance[ar?1:0]}</p><div className="mt-auto border-t border-black/10 pt-5"><p className="text-xs text-black/42">{item.rule[ar?1:0]}</p><div className="mt-4 flex gap-2">{[1,3,6,12].map(term=><span key={term} className="rounded-full border border-black/10 px-2.5 py-1 text-[9px] font-bold">{term}M</span>)}</div></div></article>})}</div></div></section>
      <section className="bg-[#EAE6DB] px-5 py-20 md:px-8 md:py-24"><div className="mx-auto max-w-[1200px]"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><QrCode size={28} className="text-[#1E7E48]"/><h2 className="mt-5 font-display text-4xl font-bold tracking-[-.04em] md:text-5xl">{ar ? 'نفس الهيكل. بدون شكل القوالب الجاهزة.' : 'The same structure. Never the template look.'}</h2></div><ol className="grid gap-px overflow-hidden rounded-2xl border border-black/10 bg-black/10 sm:grid-cols-2">{steps.map((step,index)=><li key={step} className="flex gap-4 bg-white p-5"><span className="font-mono text-[10px] text-[#1E7E48]">0{index+1}</span><p className="text-sm font-semibold leading-6">{step}</p></li>)}</ol></div><div className="mt-10 flex flex-col gap-4 border-t border-black/10 pt-7 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-md text-xs leading-5 text-black/45">{ar ? 'نربط حساب الدفع المعتمد الخاص بالنشاط؛ التفعيل النهائي يخضع لموافقة مقدم الخدمة.' : 'We connect the merchant’s approved payment account; final activation remains subject to provider approval.'}</p><div className="flex flex-wrap items-center gap-2" dir="ltr">{['Paymob','valU','Forsa','Halan'].map(name=><span key={name} className="rounded-full border border-black/12 bg-white/55 px-4 py-2 text-xs font-bold tracking-[-.02em]">{name}</span>)}</div></div></div></section>
      <section className="px-5 py-20 md:px-8 md:py-28"><div className="mx-auto grid max-w-[1200px] gap-8 rounded-[34px] bg-[#FE8C58] p-8 md:grid-cols-[1fr_auto] md:items-end md:p-12"><div><h2 className="font-display text-4xl font-bold md:text-6xl">{ar ? 'اختار نقطة البداية.' : 'Choose a starting point.'}</h2><p className="mt-4 max-w-xl text-sm leading-7 text-black/62">{ar ? 'نشوف معاً أنسب باقة للبيع، ثم نعرض السعر والنطاق النهائيين قبل البدء.' : 'We identify the strongest package together, then confirm the final scope and fixed price before work starts.'}</p></div><div className="flex flex-wrap gap-3"><Link to={localePath('/demo/membership-flow')} className="inline-flex items-center gap-2 rounded-full bg-black px-5 py-3 text-sm font-semibold text-white">{ar ? 'شوف الديمو' : 'Watch the demo'}<ArrowUpRight size={16}/></Link><a href={waLink(ar ? 'أهلاً أوتوليدز — عايز نختار باقة مناسبة لنشاطي.' : 'Hi AutoLeadss — I want to choose the right membership package for my business.')} className="rounded-full border border-black/20 px-5 py-3 text-sm font-semibold">{ar ? 'ابدأ على واتساب' : 'Start on WhatsApp'}</a></div></div></section>
    </main><Footer/><ActionDock/>
  </div>
}
