import { Helmet } from 'react-helmet-async'
import { SignIn, SignUp } from '@clerk/clerk-react'
import Logo from '../../components/Logo'
import { useI18n } from '../i18n'

/**
 * Branded split-screen wrapper around Clerk's SignIn/SignUp. Reuses the exact
 * AuthForm brand panel so the design is unchanged; Clerk renders the form fields
 * (themed to the brand via appearance variables in AuthProvider).
 */
export default function ClerkAuth({ mode }: { mode: 'signin' | 'signup' }) {
  const { isRTL } = useI18n()
  const isSignup = mode === 'signup'
  const title = isSignup
    ? (isRTL ? 'إنشاء حساب — AutoLeadss' : 'Sign up — AutoLeadss')
    : (isRTL ? 'تسجيل الدخول — AutoLeadss' : 'Log in — AutoLeadss')

  return (
    <div dir={isRTL ? 'rtl' : 'ltr'} className="grid min-h-screen lg:grid-cols-2">
      <Helmet>
        <html lang={isRTL ? 'ar' : 'en'} dir={isRTL ? 'rtl' : 'ltr'} />
        <title>{title}</title>
        <link rel="canonical" href={`https://autoleadss.com/${isSignup ? 'signup' : 'login'}`} />
      </Helmet>
      <div className="relative hidden overflow-hidden lg:flex" style={{ background: '#0A0A0B' }}>
        <div aria-hidden className="absolute inset-0 grid-bg-dark" style={{ maskImage: 'radial-gradient(ellipse at 40% 40%, black, transparent 75%)', WebkitMaskImage: 'radial-gradient(ellipse at 40% 40%, black, transparent 75%)' }} />
        <div aria-hidden className="absolute -top-20 opacity-50 blur-3xl" style={{ insetInlineStart: '-10%', width: '60%', height: '60%', background: 'radial-gradient(circle, rgba(255,92,42,0.35), transparent 65%)' }} />
        <div className="relative z-10 flex flex-col justify-between p-12">
          <Logo variant="dark" size={34} />
          <div>
            <h2 className="font-display font-bold text-white" style={{ fontSize: 'clamp(1.8rem, 3vw, 2.8rem)', letterSpacing: '-0.03em', lineHeight: 1.1 }}>
              {isRTL ? 'قمع مبيعات كامل — يولّده الذكاء الاصطناعي خلال دقائق.' : 'A complete sales funnel — generated by AI in minutes.'}
            </h2>
            <p className="mt-4 max-w-sm text-white/60">
              {isRTL ? 'صفحة هبوط، إعلانات، بوت واتساب، وسوشيال — بالعربي والإنجليزي.' : 'Landing page, ads, WhatsApp bot, and social — in Arabic and English.'}
            </p>
          </div>
          <div className="flex items-center gap-3 text-white/40 text-xs">
            <span className="h-1 w-1 rounded-full bg-accent" /> {isRTL ? 'مبني للخليج ومصر' : 'Built for the Gulf & Egypt'}
          </div>
        </div>
      </div>

      <div className="flex flex-col items-center justify-center bg-background px-6 py-10">
        <div className="mb-8 lg:hidden">
          <Logo size={30} />
        </div>
        {isSignup ? (
          <SignUp signInUrl="/login" fallbackRedirectUrl="/app/new" />
        ) : (
          <SignIn signUpUrl="/signup" fallbackRedirectUrl="/app" />
        )}
      </div>
    </div>
  )
}
