import type { Locale } from '../i18n/translations'
import type { LocalChatCopy } from '../components/LocalChat'

export const DEMO_IDS = ['cafe', 'dentist', 'gym', 'agency', 'lashes'] as const
export type DemoId = (typeof DEMO_IDS)[number]

type DemoCopy = {
  brand: string
  kind: string
  headline: string
  sub: string
  navBook: string
  cta: string
  aboutTitle: string
  about: string
  hoursTitle: string
  hours: string
  bookTitle: string
  bookBody: string
  name: string
  phone: string
  date: string
  slot: string
  submit: string
  success: string
  slots: string[]
  chat: LocalChatCopy
}

export type Demo = {
  id: DemoId
  url: string
  img: string
  accent: string
  bg: string
  fg: string
  muted: string
  copy: Record<Locale, DemoCopy>
}

export const DEMOS: Demo[] = [
  {
    id: 'cafe',
    url: 'qahwa.demo',
    img: '/demos/cafe.png',
    accent: '#4edea3',
    bg: '#0c0b0c',
    fg: '#f6f2ec',
    muted: '#a8a29e',
    copy: {
      en: {
        brand: 'Qahwa House',
        kind: 'Roastery',
        headline: 'Tactile single-origin. Road 9, Maadi.',
        sub: 'Slow brew on Cairo’s leafy avenue. Direct-trade lots from Yirgacheffe, Huila, and Haraz on a Giesen drum.',
        navBook: 'Book table',
        cta: 'Reserve tasting table',
        aboutTitle: 'The house',
        about: 'A 1940s garden villa on Road 9. Vinyl, EK43 grinders, and an unhurried brew salon.',
        hoursTitle: 'Hours',
        hours: 'Daily 7:30 AM — 11:30 PM',
        bookTitle: 'Reserve a tasting table',
        bookBody: 'No deposit. We hold the table 15 minutes.',
        name: 'Name',
        phone: 'Phone',
        date: 'Date',
        slot: 'Time',
        submit: 'Confirm tasting pass',
        success: 'Table reserved. This is a demo — no real booking was made.',
        slots: ['10:00', '13:00', '15:30', '17:30', '19:30', '21:30'],
        chat: {
          open: 'Ask barista',
          close: 'Close',
          title: 'Barista concierge',
          subtitle: 'Road 9 · FAQ on this page',
          placeholder: 'Grind, freshness, delivery…',
          send: 'Send',
          hello: 'Ahlan. Tap below for grind, freshness, delivery, or the AC library.',
          fallback: 'I only answer roastery FAQs here. Use Book table for a seat.',
          suggestions: ['Grind for V60?', "Today's roast?", 'Delivery in Cairo?', 'AC library?'],
          faq: [
            { keys: ['grind', 'v60', 'aeropress', 'french', 'turkish', 'ibrik'], a: 'Yes. EK43 is calibrated daily for V60, Aeropress, French press, and ibrik. Say the method when you order.' },
            { keys: ['fresh', 'roast', 'batch', 'today'], a: 'Beans are roasted on Road 9 within 48 hours and sealed in nitrogen tins. Batch records are under each tin.' },
            { keys: ['deliver', 'cairo', 'shipping', 'dispatch', 'maadi', 'zamalek'], a: 'Orders by 2 PM arrive same-day in Maadi. Zamalek, New Cairo, and Sheikh Zayed next morning.' },
            { keys: ['wifi', 'work', 'laptop', 'library', 'fiber'], a: 'The AC library has power, 150 Mbps fiber, and a quiet room for laptops.' },
            { keys: ['where', 'location', 'address', 'road', 'maadi'], a: 'Road 9, Maadi, Cairo. Three minutes from Degla Metro. Valet assisted.' },
            { keys: ['hour', 'open', 'close', 'time'], a: 'Daily 7:30 AM–11:30 PM. The roaster runs Mondays and Thursdays at 11:00 AM.' },
            { keys: ['book', 'table', 'reserv', 'pass'], a: 'Use Book table on this page. We hold it 15 minutes. This demo does not send WhatsApp.' },
            { keys: ['bean', 'order', 'price', 'yirgacheffe', 'bourbon'], a: 'Yirgacheffe 380 EGP, Pink Bourbon 420 EGP, cold drip 260 EGP, brioche 110 EGP. Orders here are a demo.' },
          ],
        },
      },
      ar: {
        brand: 'قهوة هاوس',
        kind: 'محمصة',
        headline: 'أصول مفردة. شارع ٩، المعادي.',
        sub: 'تخمير بطيء على شارع المعادي. لوتات من يرقا تشيف وويلا وحراز على درم جيزن.',
        navBook: 'احجز ترابيزة',
        cta: 'احجز ترابيزة تذوق',
        aboutTitle: 'البيت',
        about: 'فيلا جنينة من الأربعينات على شارع ٩. فينيل وجريندر هادي وصالة تخمير من غير عجلة.',
        hoursTitle: 'المواعيد',
        hours: 'يومياً ٧:٣٠ ص — ١١:٣٠ م',
        bookTitle: 'احجز ترابيزة تذوق',
        bookBody: 'من غير ديبوزيت. نمسك الترابيزة ربع ساعة.',
        name: 'الاسم',
        phone: 'الموبايل',
        date: 'التاريخ',
        slot: 'الوقت',
        submit: 'تأكيد الباس',
        success: 'الترابيزة اتحجزت. ده ديمو — مفيش حجز حقيقي.',
        slots: ['١٠:٠٠', '١٣:٠٠', '١٥:٣٠', '١٧:٣٠', '١٩:٣٠', '٢١:٣٠'],
        chat: {
          open: 'اسأل الباريستا',
          close: 'إغلاق',
          title: 'كونسيرج الباريستا',
          subtitle: 'شارع ٩ · أسئلة على الصفحة',
          placeholder: 'طحن، طزاجة، توصيل…',
          send: 'إرسال',
          hello: 'أهلاً. اسأل عن الطحن أو التحميص أو التوصيل أو المكتبة.',
          fallback: 'بجاوب أسئلة المحمصة هنا. للحجز استخدم احجز ترابيزة.',
          suggestions: ['طحن V60؟', 'تحميص النهاردة؟', 'توصيل القاهرة؟', 'المكتبة؟'],
          faq: [
            { keys: ['طحن', 'v60', 'ايرو', 'فرنش', 'تركي'], a: 'نعم. EK43 متعاير يومياً لـ V60 والأيروبريس والفرنش والإبريق. قول الطريقة وأنت بتطلب.' },
            { keys: ['طازج', 'تحميص', 'دفعة', 'نهاردة'], a: 'البن بيتحمص على شارع ٩ خلال ٤٨ ساعة ويتقفل نيتروجين. رقم الدفعة تحت العلبة.' },
            { keys: ['توصيل', 'قاهرة', 'معادي', 'زمالك'], a: 'الطلب قبل ٢ بيوصل نفس اليوم في المعادي. الزمالك والقاهرة الجديدة والشيخ زايد تاني يوم الصبح.' },
            { keys: ['واي', 'نت', 'لابتوب', 'مكتبة', 'wifi'], a: 'مكتبة التكييف فيها باور وفايبر ١٥٠ وغرفة هادية للابتوب.' },
            { keys: ['فين', 'عنوان', 'شارع', 'معادي', 'مكان'], a: 'شارع ٩، المعادي، القاهرة. ٣ دقايق من مترو دجلة. فاليه.' },
            { keys: ['ميعاد', 'ساعة', 'فاتح', 'قفل'], a: 'يومياً ٧:٣٠ ص–١١:٣٠ م. المحمصة الاثنين والخميس الساعة ١١ ص.' },
            { keys: ['حجز', 'ترابيزة', 'باس'], a: 'استخدم احجز ترابيزة على الصفحة. نمسكها ربع ساعة. الديمو مش بيبعت واتساب.' },
            { keys: ['بن', 'طلب', 'سعر', 'إثيوبيا'], a: 'يرقا تشيف ٣٨٠، بينك بوربون ٤٢٠، كولد دريب ٢٦٠، بريوش ١١٠. الطلب هنا ديمو.' },
          ],
        },
      },
    },
  },
  {
    id: 'dentist',
    url: 'niledental.demo',
    img: '/demos/dentist.png',
    accent: '#2A9D8F',
    bg: '#F3F7F6',
    fg: '#102826',
    muted: '#4F6B67',
    copy: {
      en: {
        brand: 'Nile Dental',
        kind: 'Clinic',
        headline: 'Calm dentistry. Clear answers.',
        sub: 'Checkups, whitening, and a first visit that does not rush you.',
        navBook: 'Book a visit',
        cta: 'Book a checkup',
        aboutTitle: 'The clinic',
        about: 'A quiet practice in New Cairo. We explain before we touch anything. Same-day emergencies when we can.',
        hoursTitle: 'Hours',
        hours: 'Sun–Thu 10:00–20:00 · Sat 11:00–16:00',
        bookTitle: 'Book a visit',
        bookBody: 'Pick a slot. We confirm by phone the day before.',
        name: 'Name',
        phone: 'Phone',
        date: 'Date',
        slot: 'Time',
        submit: 'Book visit',
        success: 'Visit reserved. This is a demo — no real appointment was made.',
        slots: ['10:30', '12:00', '14:30', '16:00', '18:30'],
        chat: {
          open: 'Open chat',
          close: 'Close chat',
          title: 'Nile Dental',
          subtitle: 'FAQ bot · on this page',
          placeholder: 'First visit, whitening, hours…',
          send: 'Send',
          hello: 'Ask about a first visit, whitening, or hours.',
          fallback: 'I only answer clinic FAQs here. Use Book a visit for a slot.',
          suggestions: ['First visit?', 'Do you whiten?', 'What are the hours?'],
          faq: [
            { keys: ['first', 'new', 'visit'], a: 'First visit is 40 minutes. We look, we explain, we plan. No pressure to start treatment that day.' },
            { keys: ['white', 'whiten', 'bleach'], a: 'Yes. In-chair whitening after a checkup. We will tell you if your enamel is ready.' },
            { keys: ['hour', 'open', 'time'], a: 'Sun–Thu 10:00–20:00. Saturday 11:00–16:00. Closed Friday.' },
            { keys: ['book', 'appoint', 'slot'], a: 'Use Book a visit on this page. We call the day before.' },
            { keys: ['emerg', 'pain', 'urgent'], a: 'Call the clinic number on the page for same-day pain. The bot cannot book emergencies.' },
          ],
        },
      },
      ar: {
        brand: 'نايل دينتال',
        kind: 'عيادة',
        headline: 'أسنان بهدوء. وإجابات واضحة.',
        sub: 'كشف، تبييض، وأول زيارة من غير استعجال.',
        navBook: 'احجز زيارة',
        cta: 'احجز كشف',
        aboutTitle: 'العيادة',
        about: 'عيادة هادية في القاهرة الجديدة. نشرح قبل ما نلمس حاجة. طوارئ في نفس اليوم لما نقدر.',
        hoursTitle: 'المواعيد',
        hours: 'أحد–خميس ١٠–٨ م · سبت ١١–٤ م',
        bookTitle: 'احجز زيارة',
        bookBody: 'اختار موعد. نأكد بالتليفون قبلها بيوم.',
        name: 'الاسم',
        phone: 'الموبايل',
        date: 'التاريخ',
        slot: 'الوقت',
        submit: 'تأكيد الزيارة',
        success: 'الزيارة اتحجزت. ده ديمو — مفيش موعد حقيقي.',
        slots: ['١٠:٣٠', '١٢:٠٠', '١٤:٣٠', '١٦:٠٠', '١٨:٣٠'],
        chat: {
          open: 'فتح الدردشة',
          close: 'إغلاق الدردشة',
          title: 'نايل دينتال',
          subtitle: 'بوت الأسئلة · على الصفحة',
          placeholder: 'أول زيارة، تبييض، المواعيد…',
          send: 'إرسال',
          hello: 'اسأل عن أول زيارة أو التبييض أو المواعيد.',
          fallback: 'بجاوب أسئلة العيادة هنا. للحجز استخدم احجز زيارة.',
          suggestions: ['أول زيارة؟', 'بتبيضوا؟', 'المواعيد؟'],
          faq: [
            { keys: ['أول', 'جديد', 'زيارة'], a: 'أول زيارة ٤٠ دقيقة. نبص ونشرح ونخطط. من غير ضغط تبدأ علاج يومها.' },
            { keys: ['تبيض', 'تبييض', 'لون'], a: 'نعم. تبييض في العيادة بعد كشف. نقولك لو المينا جاهزة.' },
            { keys: ['ميعاد', 'ساعة', 'فاتح'], a: 'أحد–خميس ١٠ ص–٨ م. السبت ١١–٤. الجمعة مغلق.' },
            { keys: ['حجز', 'موعد', 'كشف'], a: 'استخدم احجز زيارة على الصفحة. نتصل قبلها بيوم.' },
            { keys: ['طوارئ', 'ألم', 'وجع'], a: 'اتصل برقم العيادة للطوارئ في نفس اليوم. البوت مش بيحجز الطوارئ.' },
          ],
        },
      },
    },
  },
  {
    id: 'gym',
    url: 'forgegym.demo',
    img: '/demos/gym.png',
    accent: '#C8F542',
    bg: '#0C0C0D',
    fg: '#F4F4F0',
    muted: '#9A9A90',
    copy: {
      en: {
        brand: 'Forge',
        kind: 'Gym',
        headline: 'Show up. Get heavy.',
        sub: 'Strength, classes, and a trial that actually lets you lift.',
        navBook: 'Book a trial',
        cta: 'Book a trial class',
        aboutTitle: 'The floor',
        about: 'A warehouse gym. Barbells, a 6am class, and coaches who watch your back squat. No juice bar theatre.',
        hoursTitle: 'Hours',
        hours: 'Sat–Thu 6:00–23:00 · Fri 8:00–20:00',
        bookTitle: 'Book a trial',
        bookBody: 'One free class. Wear shoes you can lift in.',
        name: 'Name',
        phone: 'Phone',
        date: 'Date',
        slot: 'Class',
        submit: 'Book trial',
        success: 'Trial held. This is a demo — no real class was booked.',
        slots: ['06:30 Lift', '09:00 Cond', '12:00 Lift', '18:30 Class', '20:00 Open'],
        chat: {
          open: 'Open chat',
          close: 'Close chat',
          title: 'Forge',
          subtitle: 'FAQ bot · on this page',
          placeholder: 'Trial, hours, classes…',
          send: 'Send',
          hello: 'Ask about a trial, hours, or what to bring.',
          fallback: 'I only answer gym FAQs here. Use Book a trial for a class.',
          suggestions: ['Is the trial free?', 'What are the hours?', 'What do I bring?'],
          faq: [
            { keys: ['trial', 'free', 'first'], a: 'Yes. One free class. Book a trial on this page. Coach will scale the session.' },
            { keys: ['hour', 'open', 'time'], a: 'Sat–Thu 6:00–23:00. Friday 8:00–20:00.' },
            { keys: ['bring', 'wear', 'shoes', 'what'], a: 'Flat shoes, water, a towel. We have chalk. No perfume on the floor.' },
            { keys: ['book', 'class', 'slot'], a: 'Use Book a trial on this page. Pick a class time.' },
            { keys: ['price', 'member', 'cost'], a: 'Membership is quoted in person after the trial. The bot does not take payment.' },
          ],
        },
      },
      ar: {
        brand: 'فورج',
        kind: 'جيم',
        headline: 'تعالى. ارفع تقيل.',
        sub: 'قوة وكلاسات وتجربة تخليك ترفع فعلاً.',
        navBook: 'احجز تجربة',
        cta: 'احجز كلاس تجريبي',
        aboutTitle: 'الأرض',
        about: 'جيم في مخزن. باربلز وكلاس ٦ الصبح وكوتشز بيراقبوا السكوات. من غير مسرح عصائر.',
        hoursTitle: 'المواعيد',
        hours: 'سبت–خميس ٦ ص–١١ م · جمعة ٨–٨ م',
        bookTitle: 'احجز تجربة',
        bookBody: 'كلاس مجاني واحد. البس جزمة ترفع فيها.',
        name: 'الاسم',
        phone: 'الموبايل',
        date: 'التاريخ',
        slot: 'الكلاس',
        submit: 'تأكيد التجربة',
        success: 'التجربة اتحجزت. ده ديمو — مفيش كلاس حقيقي.',
        slots: ['٦:٣٠ رفع', '٩:٠٠ كوند', '١٢:٠٠ رفع', '٦:٣٠ م', '٨:٠٠ مفتوح'],
        chat: {
          open: 'فتح الدردشة',
          close: 'إغلاق الدردشة',
          title: 'فورج',
          subtitle: 'بوت الأسئلة · على الصفحة',
          placeholder: 'تجربة، مواعيد، كلاسات…',
          send: 'إرسال',
          hello: 'اسأل عن التجربة أو المواعيد أو تجيب إيه.',
          fallback: 'بجاوب أسئلة الجيم هنا. للحجز استخدم احجز تجربة.',
          suggestions: ['التجربة مجانية؟', 'المواعيد؟', 'أجيب إيه؟'],
          faq: [
            { keys: ['تجربة', 'مجاني', 'أول', 'فري'], a: 'نعم. كلاس مجاني واحد. احجز تجربة على الصفحة. الكوتش يظبط المستوى.' },
            { keys: ['ميعاد', 'ساعة', 'فاتح'], a: 'سبت–خميس ٦ ص–١١ م. الجمعة ٨ ص–٨ م.' },
            { keys: ['أجيب', 'لبس', 'جزمة'], a: 'جزمة فلات، مية، فوطة. عندنا طباشير. من غير بيرفيوم على الأرض.' },
            { keys: ['حجز', 'كلاس', 'موعد'], a: 'استخدم احجز تجربة على الصفحة. اختار وقت الكلاس.' },
            { keys: ['سعر', 'اشتراك', 'كام'], a: 'الاشتراك يتقال بعد التجربة في الجيم. البوت مش بياخد فلوس.' },
          ],
        },
      },
    },
  },
  {
    id: 'agency',
    url: 'noonstudio.demo',
    img: '/demos/agency.png',
    accent: '#E0A84A',
    bg: '#141210',
    fg: '#F3EDE4',
    muted: '#A89B8C',
    copy: {
      en: {
        brand: 'Noon Studio',
        kind: 'Agency',
        headline: 'Brand work. Book the hour.',
        sub: 'A small studio. Discovery calls, not a contact form that disappears.',
        navBook: 'Book a call',
        cta: 'Book a discovery call',
        aboutTitle: 'The studio',
        about: 'Identity, sites, and campaigns for teams who already know what they sell. We start with a 40-minute desk hour.',
        hoursTitle: 'Hours',
        hours: 'Sun–Thu 10:00–18:00',
        bookTitle: 'Book a discovery call',
        bookBody: 'Forty minutes. Camera on. Bring the current site and what is broken.',
        name: 'Name',
        phone: 'Phone',
        date: 'Date',
        slot: 'Time',
        submit: 'Book the hour',
        success: 'Call held. This is a demo — no real meeting was booked.',
        slots: ['10:00', '11:30', '13:00', '15:00', '16:30'],
        chat: {
          open: 'Open chat',
          close: 'Close chat',
          title: 'Noon',
          subtitle: 'FAQ bot · on this page',
          placeholder: 'Calls, timing, what you do…',
          send: 'Send',
          hello: 'Ask how booking works, or what the studio does.',
          fallback: 'I only answer studio FAQs here. Use Book a call for a slot.',
          suggestions: ['How do I book?', 'What do you do?', 'How long is the call?'],
          faq: [
            { keys: ['book', 'call', 'appoint', 'slot'], a: 'Use Book a discovery call on this page. Forty minutes. We send a calendar note after you submit.' },
            { keys: ['do you', 'service', 'work', 'what'], a: 'Brand identity, campaign sites, and launch work. Not social media retainers.' },
            { keys: ['long', 'minute', 'duration', 'hour'], a: 'The first meeting is 40 minutes. No deck. Bring the live URL.' },
            { keys: ['price', 'cost', 'quote'], a: 'We quote after the call. The bot does not send prices.' },
            { keys: ['where', 'cairo', 'office'], a: 'Garden City studio, by appointment only.' },
          ],
        },
      },
      ar: {
        brand: 'نون ستوديو',
        kind: 'وكالة',
        headline: 'شغل براند. احجز الساعة.',
        sub: 'ستوديو صغير. مكالمة تعارف، مش فورم بيختفي.',
        navBook: 'احجز مكالمة',
        cta: 'احجز مكالمة تعارف',
        aboutTitle: 'الاستوديو',
        about: 'هوية ومواقع وحملات لفرق عارفة بتبيع إيه. نبدأ بساعة مكتب ٤٠ دقيقة.',
        hoursTitle: 'المواعيد',
        hours: 'أحد–خميس ١٠ ص–٦ م',
        bookTitle: 'احجز مكالمة تعارف',
        bookBody: 'أربعين دقيقة. الكاميرا مفتوحة. هات الموقع الحالي وإيه المكسور.',
        name: 'الاسم',
        phone: 'الموبايل',
        date: 'التاريخ',
        slot: 'الوقت',
        submit: 'حجز الساعة',
        success: 'المكالمة اتحجزت. ده ديمو — مفيش ميتنج حقيقي.',
        slots: ['١٠:٠٠', '١١:٣٠', '١٣:٠٠', '١٥:٠٠', '١٦:٣٠'],
        chat: {
          open: 'فتح الدردشة',
          close: 'إغلاق الدردشة',
          title: 'نون',
          subtitle: 'بوت الأسئلة · على الصفحة',
          placeholder: 'حجز، وقت، بتقدموا إيه…',
          send: 'إرسال',
          hello: 'اسأل عن الحجز أو شغل الاستوديو.',
          fallback: 'بجاوب أسئلة الاستوديو هنا. للحجز استخدم احجز مكالمة.',
          suggestions: ['أحجز إزاي؟', 'بتعملوا إيه؟', 'المكالمة كام دقيقة؟'],
          faq: [
            { keys: ['حجز', 'مكالمة', 'موعد'], a: 'استخدم احجز مكالمة تعارف على الصفحة. ٤٠ دقيقة. بعد الإرسال نبعت نوت في التقويم.' },
            { keys: ['شغل', 'خدمة', 'تعمل'], a: 'هوية براند ومواقع حملات وشغل إطلاق. مش سوشيال ميديا ريتينر.' },
            { keys: ['دقيق', 'مدة', 'ساعة', 'طول'], a: 'أول اجتماع ٤٠ دقيقة. من غير ديك. هات الرابط الحي.' },
            { keys: ['سعر', 'تكلفة', 'كام'], a: 'نسعّر بعد المكالمة. البوت مش بيبعت أسعار.' },
            { keys: ['فين', 'مكتب', 'قاهرة'], a: 'ستوديو جاردن سيتي، بموعد فقط.' },
          ],
        },
      },
    },
  },
  {
    id: 'lashes',
    url: 'lashcartel.demo',
    img: '/demos/lashes.png',
    accent: '#E8C9A8',
    bg: '#0B0A0C',
    fg: '#F6F0E8',
    muted: '#A89B8C',
    copy: {
      en: {
        brand: 'Lash Cartel',
        kind: 'Lash studio',
        headline: 'The set is the whole look.',
        sub: 'Zamalek. Classic, volume, hybrid, fills. Soft light, mapped lashes, a bed you book on the page.',
        navBook: 'Book a set',
        cta: 'Book a lash set',
        aboutTitle: 'The studio',
        about: 'A quiet room off 26th of July. We map, we glue, we photograph the line. No walk-ins after 18:00.',
        hoursTitle: 'Hours',
        hours: 'Sat–Thu 10:00–20:00 · Fri 12:00–18:00',
        bookTitle: 'Book a set',
        bookBody: 'Classic, volume, hybrid, or a fill. We hold the bed 15 minutes.',
        name: 'Name',
        phone: 'Phone',
        date: 'Date',
        slot: 'Time',
        submit: 'Hold the bed',
        success: 'Bed held. This is a demo — no real appointment was made.',
        slots: ['10:30', '12:00', '14:00', '16:30', '18:00'],
        chat: {
          open: 'Ask the desk',
          close: 'Close',
          title: 'Lash Cartel',
          subtitle: 'FAQ bot · on this page',
          placeholder: 'Classic vs volume, fills, hours…',
          send: 'Send',
          hello: 'Ask about classic vs volume, fills, patch tests, or hours.',
          fallback: 'I only answer studio FAQs here. Use Book a set for a bed.',
          suggestions: ['Classic or volume?', 'How long is a fill?', 'Patch test?', 'Hours?'],
          faq: [
            { keys: ['classic', 'volume', 'hybrid', 'set'], a: 'Classic is one-to-one. Volume is fans. Hybrid mixes both. Pick the set on the booking form.' },
            { keys: ['fill', 'infill', 'weeks'], a: 'Fills are 2–3 weeks after a full set, about 75 minutes. Book a fill slot on this page.' },
            { keys: ['patch', 'allergy', 'glue'], a: 'New clients: a patch test 48 hours before. Tell us if your eyes run.' },
            { keys: ['hour', 'open', 'time'], a: 'Sat–Thu 10:00–20:00. Friday 12:00–18:00.' },
            { keys: ['where', 'zamalek', 'location', 'address'], a: 'Zamalek, off 26th of July. Street parking on the corniche side.' },
            { keys: ['book', 'appoint', 'slot'], a: 'Use Book a set on this page. This demo does not send WhatsApp.' },
            { keys: ['price', 'cost', 'egp'], a: 'Classic 1,200 EGP, volume 1,800, hybrid 1,500, fill 850. Quoted on a live site after we see the lash line.' },
          ],
        },
      },
      ar: {
        brand: 'لاش كارتل',
        kind: 'استوديو رموش',
        headline: 'الست هو الشكل كله.',
        sub: 'الزمالك. كلاسيك، فوليوم، هايبريد، فيل. نور هادي ورموش متظبطة وسرير بتحجزه على الصفحة.',
        navBook: 'احجز ست',
        cta: 'احجز ست رموش',
        aboutTitle: 'الاستوديو',
        about: 'أوضة هادية جنب ٢٦ يوليو. بنخطط وبنلزق وبنصور الخط. من غير دخول من غير معاد بعد ٦.',
        hoursTitle: 'المواعيد',
        hours: 'سبت–خميس ١٠ ص–٨ م · جمعة ١٢–٦ م',
        bookTitle: 'احجز ست',
        bookBody: 'كلاسيك أو فوليوم أو هايبريد أو فيل. نمسك السرير ربع ساعة.',
        name: 'الاسم',
        phone: 'الموبايل',
        date: 'التاريخ',
        slot: 'الوقت',
        submit: 'تأكيد السرير',
        success: 'السرير اتحجز. ده ديمو — مفيش معاد حقيقي.',
        slots: ['١٠:٣٠', '١٢:٠٠', '١٤:٠٠', '١٦:٣٠', '١٨:٠٠'],
        chat: {
          open: 'اسأل الديسك',
          close: 'إغلاق',
          title: 'لاش كارتل',
          subtitle: 'بوت الأسئلة · على الصفحة',
          placeholder: 'كلاسيك ولا فوليوم، فيل، مواعيد…',
          send: 'إرسال',
          hello: 'اسأل عن الكلاسيك والفوليوم والفيل أو اختبار اللزق أو المواعيد.',
          fallback: 'بجاوب أسئلة الاستوديو هنا. للحجز استخدم احجز ست.',
          suggestions: ['كلاسيك ولا فوليوم؟', 'الفيل كام؟', 'اختبار لزق؟', 'المواعيد؟'],
          faq: [
            { keys: ['كلاسيك', 'فوليوم', 'هايبريد', 'ست'], a: 'الكلاسيك واحد لواحد. الفوليوم فانز. الهايبريد الاتنين. اختار الست في فورم الحجز.' },
            { keys: ['فيل', 'تعبئة', 'أسبوع'], a: 'الفيل بعد أسبوعين–تلاتة من الست الكامل، حوالي ٧٥ دقيقة. احجز فيل من الصفحة.' },
            { keys: ['اختبار', 'حساسية', 'لزق'], a: 'عملاء جدد: اختبار لزق قبلها بـ ٤٨ ساعة. قوليلنا لو عينك بتدمع.' },
            { keys: ['ميعاد', 'ساعة', 'فاتح'], a: 'سبت–خميس ١٠ ص–٨ م. الجمعة ١٢–٦ م.' },
            { keys: ['فين', 'زمالك', 'عنوان', 'مكان'], a: 'الزمالك، جنب ٢٦ يوليو. ركن ناحية الكورنيش.' },
            { keys: ['حجز', 'موعد', 'سرير'], a: 'استخدم احجز ست على الصفحة. الديمو مش بيبعت واتساب.' },
            { keys: ['سعر', 'كام', 'جنيه'], a: 'كلاسيك ١٬٢٠٠، فوليوم ١٬٨٠٠، هايبريد ١٬٥٠٠، فيل ٨٥٠. على موقع حي السعر بعد ما نشوف خط الرمش.' },
          ],
        },
      },
    },
  },
]

export function demoById(id: string | undefined): Demo | undefined {
  return DEMOS.find(d => d.id === id)
}
