import type { Locale } from '../i18n/translations'
import type { LocalChatCopy } from '../components/LocalChat'

export const DEMO_IDS = ['cafe', 'dentist', 'gym', 'agency'] as const
export type DemoId = (typeof DEMO_IDS)[number]

type DemoCopy = {
  brand: string
  kind: string
  headline: string
  sub: string
  navBook: string
  cta: string
  aboutTitle: string
  about: string
  hoursTitle: string
  hours: string
  bookTitle: string
  bookBody: string
  name: string
  phone: string
  date: string
  slot: string
  submit: string
  success: string
  slots: string[]
  chat: LocalChatCopy
}

export type Demo = {
  id: DemoId
  url: string
  img: string
  accent: string
  bg: string
  fg: string
  muted: string
  copy: Record<Locale, DemoCopy>
}

export const DEMOS: Demo[] = [
  {
    id: 'cafe',
    url: 'qahwa.demo',
    img: '/demos/cafe.png',
    accent: '#C45C26',
    bg: '#F6EFE6',
    fg: '#2A1C14',
    muted: '#6E584C',
    copy: {
      en: {
        brand: 'Qahwa House',
        kind: 'Cafe',
        headline: 'Coffee, slow. Cairo, always.',
        sub: 'Zamalek. Beans, bread, a table by the window.',
        navBook: 'Book a table',
        cta: 'Book a table',
        aboutTitle: 'The house',
        about: 'A small cafe. Filter, espresso, and a kitchen that stops at 4. Come for one cup. Stay for the second.',
        hoursTitle: 'Hours',
        hours: 'Sat–Thu 8:00–23:00 · Fri 9:00–24:00',
        bookTitle: 'Reserve a table',
        bookBody: 'Two to four people. We hold the table for 15 minutes.',
        name: 'Name',
        phone: 'Phone',
        date: 'Date',
        slot: 'Time',
        submit: 'Confirm table',
        success: 'Table held. This is a demo — no real booking was made.',
        slots: ['09:00', '11:30', '14:00', '17:00', '20:00'],
        chat: {
          open: 'Open chat',
          close: 'Close chat',
          title: 'Qahwa',
          subtitle: 'FAQ bot · on this page',
          placeholder: 'Hours, location, wifi…',
          send: 'Send',
          hello: 'Ask about hours, the kitchen, or how to book a table.',
          fallback: 'I only answer cafe FAQs here. Use Book a table for a seat.',
          suggestions: ['What are the hours?', 'Where are you?', 'Do you have wifi?'],
          faq: [
            { keys: ['hour', 'open', 'close', 'time'], a: 'Sat–Thu 8:00–23:00. Friday 9:00–24:00.' },
            { keys: ['where', 'location', 'address', 'zamalek'], a: 'Zamalek, Cairo. A two-minute walk from the bridge.' },
            { keys: ['wifi', 'work', 'laptop'], a: 'Yes. Wifi is on. Laptops are fine until 18:00.' },
            { keys: ['book', 'table', 'reserv'], a: 'Use Book a table on this page. We hold it 15 minutes.' },
            { keys: ['food', 'kitchen', 'menu', 'breakfast'], a: 'Kitchen until 16:00. Coffee all day.' },
          ],
        },
      },
      ar: {
        brand: 'قهوة هاوس',
        kind: 'مقهى',
        headline: 'قهوة بهدوء. القاهرة دايماً.',
        sub: 'الزمالك. بن، عيش، ترابيزة جنب الشباك.',
        navBook: 'احجز ترابيزة',
        cta: 'احجز ترابيزة',
        aboutTitle: 'البيت',
        about: 'مقهى صغير. فلتر وإسبريسو ومطبخ يقف الساعة ٤. تعالى على فنجان. اقعد على التاني.',
        hoursTitle: 'المواعيد',
        hours: 'سبت–خميس ٨–١١ م · جمعة ٩–١٢ ص',
        bookTitle: 'احجز ترابيزة',
        bookBody: 'من اثنين لأربعة. نمسك الترابيزة ربع ساعة.',
        name: 'الاسم',
        phone: 'الموبايل',
        date: 'التاريخ',
        slot: 'الوقت',
        submit: 'تأكيد الحجز',
        success: 'الترابيزة اتحجزت. ده ديمو — مفيش حجز حقيقي.',
        slots: ['٠٩:٠٠', '١١:٣٠', '١٤:٠٠', '١٧:٠٠', '٢٠:٠٠'],
        chat: {
          open: 'فتح الدردشة',
          close: 'إغلاق الدردشة',
          title: 'قهوة',
          subtitle: 'بوت الأسئلة · على الصفحة',
          placeholder: 'المواعيد، المكان، الواي فاي…',
          send: 'إرسال',
          hello: 'اسأل عن المواعيد أو المطبخ أو حجز ترابيزة.',
          fallback: 'بجاوب أسئلة المقهى هنا. للحجز استخدم احجز ترابيزة.',
          suggestions: ['المواعيد؟', 'فين المكان؟', 'في واي فاي؟'],
          faq: [
            { keys: ['ميعاد', 'ساعة', 'فاتح', 'قفل'], a: 'سبت–خميس ٨ صباحاً–١١ مساءً. الجمعة ٩–١٢.' },
            { keys: ['فين', 'عنوان', 'زمالك', 'مكان'], a: 'الزمالك، القاهرة. دقيقتين من الكوبري.' },
            { keys: ['واي', 'نت', 'لابتوب', 'wifi'], a: 'نعم. الواي فاي شغال. اللابتوب لحد ٦ مساءً.' },
            { keys: ['حجز', 'ترابيزة', 'طاولة'], a: 'استخدم احجز ترابيزة على الصفحة. نمسكها ربع ساعة.' },
            { keys: ['أكل', 'مطبخ', 'فطار', 'منيو'], a: 'المطبخ لحد ٤ العصر. القهوة طول اليوم.' },
          ],
        },
      },
    },
  },
  {
    id: 'dentist',
    url: 'niledental.demo',
    img: '/demos/dentist.png',
    accent: '#2A9D8F',
    bg: '#F3F7F6',
    fg: '#102826',
    muted: '#4F6B67',
    copy: {
      en: {
        brand: 'Nile Dental',
        kind: 'Clinic',
        headline: 'Calm dentistry. Clear answers.',
        sub: 'Checkups, whitening, and a first visit that does not rush you.',
        navBook: 'Book a visit',
        cta: 'Book a checkup',
        aboutTitle: 'The clinic',
        about: 'A quiet practice in New Cairo. We explain before we touch anything. Same-day emergencies when we can.',
        hoursTitle: 'Hours',
        hours: 'Sun–Thu 10:00–20:00 · Sat 11:00–16:00',
        bookTitle: 'Book a visit',
        bookBody: 'Pick a slot. We confirm by phone the day before.',
        name: 'Name',
        phone: 'Phone',
        date: 'Date',
        slot: 'Time',
        submit: 'Book visit',
        success: 'Visit reserved. This is a demo — no real appointment was made.',
        slots: ['10:30', '12:00', '14:30', '16:00', '18:30'],
        chat: {
          open: 'Open chat',
          close: 'Close chat',
          title: 'Nile Dental',
          subtitle: 'FAQ bot · on this page',
          placeholder: 'First visit, whitening, hours…',
          send: 'Send',
          hello: 'Ask about a first visit, whitening, or hours.',
          fallback: 'I only answer clinic FAQs here. Use Book a visit for a slot.',
          suggestions: ['First visit?', 'Do you whiten?', 'What are the hours?'],
          faq: [
            { keys: ['first', 'new', 'visit'], a: 'First visit is 40 minutes. We look, we explain, we plan. No pressure to start treatment that day.' },
            { keys: ['white', 'whiten', 'bleach'], a: 'Yes. In-chair whitening after a checkup. We will tell you if your enamel is ready.' },
            { keys: ['hour', 'open', 'time'], a: 'Sun–Thu 10:00–20:00. Saturday 11:00–16:00. Closed Friday.' },
            { keys: ['book', 'appoint', 'slot'], a: 'Use Book a visit on this page. We call the day before.' },
            { keys: ['emerg', 'pain', 'urgent'], a: 'Call the clinic number on the page for same-day pain. The bot cannot book emergencies.' },
          ],
        },
      },
      ar: {
        brand: 'نايل دينتال',
        kind: 'عيادة',
        headline: 'أسنان بهدوء. وإجابات واضحة.',
        sub: 'كشف، تبييض، وأول زيارة من غير استعجال.',
        navBook: 'احجز زيارة',
        cta: 'احجز كشف',
        aboutTitle: 'العيادة',
        about: 'عيادة هادية في القاهرة الجديدة. نشرح قبل ما نلمس حاجة. طوارئ في نفس اليوم لما نقدر.',
        hoursTitle: 'المواعيد',
        hours: 'أحد–خميس ١٠–٨ م · سبت ١١–٤ م',
        bookTitle: 'احجز زيارة',
        bookBody: 'اختار موعد. نأكد بالتليفون قبلها بيوم.',
        name: 'الاسم',
        phone: 'الموبايل',
        date: 'التاريخ',
        slot: 'الوقت',
        submit: 'تأكيد الزيارة',
        success: 'الزيارة اتحجزت. ده ديمو — مفيش موعد حقيقي.',
        slots: ['١٠:٣٠', '١٢:٠٠', '١٤:٣٠', '١٦:٠٠', '١٨:٣٠'],
        chat: {
          open: 'فتح الدردشة',
          close: 'إغلاق الدردشة',
          title: 'نايل دينتال',
          subtitle: 'بوت الأسئلة · على الصفحة',
          placeholder: 'أول زيارة، تبييض، المواعيد…',
          send: 'إرسال',
          hello: 'اسأل عن أول زيارة أو التبييض أو المواعيد.',
          fallback: 'بجاوب أسئلة العيادة هنا. للحجز استخدم احجز زيارة.',
          suggestions: ['أول زيارة؟', 'بتبيضوا؟', 'المواعيد؟'],
          faq: [
            { keys: ['أول', 'جديد', 'زيارة'], a: 'أول زيارة ٤٠ دقيقة. نبص ونشرح ونخطط. من غير ضغط تبدأ علاج يومها.' },
            { keys: ['تبيض', 'تبييض', 'لون'], a: 'نعم. تبييض في العيادة بعد كشف. نقولك لو المينا جاهزة.' },
            { keys: ['ميعاد', 'ساعة', 'فاتح'], a: 'أحد–خميس ١٠ ص–٨ م. السبت ١١–٤. الجمعة مغلق.' },
            { keys: ['حجز', 'موعد', 'كشف'], a: 'استخدم احجز زيارة على الصفحة. نتصل قبلها بيوم.' },
            { keys: ['طوارئ', 'ألم', 'وجع'], a: 'اتصل برقم العيادة للطوارئ في نفس اليوم. البوت مش بيحجز الطوارئ.' },
          ],
        },
      },
    },
  },
  {
    id: 'gym',
    url: 'forgegym.demo',
    img: '/demos/gym.png',
    accent: '#C8F542',
    bg: '#0C0C0D',
    fg: '#F4F4F0',
    muted: '#9A9A90',
    copy: {
      en: {
        brand: 'Forge',
        kind: 'Gym',
        headline: 'Show up. Get heavy.',
        sub: 'Strength, classes, and a trial that actually lets you lift.',
        navBook: 'Book a trial',
        cta: 'Book a trial class',
        aboutTitle: 'The floor',
        about: 'A warehouse gym. Barbells, a 6am class, and coaches who watch your back squat. No juice bar theatre.',
        hoursTitle: 'Hours',
        hours: 'Sat–Thu 6:00–23:00 · Fri 8:00–20:00',
        bookTitle: 'Book a trial',
        bookBody: 'One free class. Wear shoes you can lift in.',
        name: 'Name',
        phone: 'Phone',
        date: 'Date',
        slot: 'Class',
        submit: 'Book trial',
        success: 'Trial held. This is a demo — no real class was booked.',
        slots: ['06:30 Lift', '09:00 Cond', '12:00 Lift', '18:30 Class', '20:00 Open'],
        chat: {
          open: 'Open chat',
          close: 'Close chat',
          title: 'Forge',
          subtitle: 'FAQ bot · on this page',
          placeholder: 'Trial, hours, classes…',
          send: 'Send',
          hello: 'Ask about a trial, hours, or what to bring.',
          fallback: 'I only answer gym FAQs here. Use Book a trial for a class.',
          suggestions: ['Is the trial free?', 'What are the hours?', 'What do I bring?'],
          faq: [
            { keys: ['trial', 'free', 'first'], a: 'Yes. One free class. Book a trial on this page. Coach will scale the session.' },
            { keys: ['hour', 'open', 'time'], a: 'Sat–Thu 6:00–23:00. Friday 8:00–20:00.' },
            { keys: ['bring', 'wear', 'shoes', 'what'], a: 'Flat shoes, water, a towel. We have chalk. No perfume on the floor.' },
            { keys: ['book', 'class', 'slot'], a: 'Use Book a trial on this page. Pick a class time.' },
            { keys: ['price', 'member', 'cost'], a: 'Membership is quoted in person after the trial. The bot does not take payment.' },
          ],
        },
      },
      ar: {
        brand: 'فورج',
        kind: 'جيم',
        headline: 'تعالى. ارفع تقيل.',
        sub: 'قوة وكلاسات وتجربة تخليك ترفع فعلاً.',
        navBook: 'احجز تجربة',
        cta: 'احجز كلاس تجريبي',
        aboutTitle: 'الأرض',
        about: 'جيم في مخزن. باربلز وكلاس ٦ الصبح وكوتشز بيراقبوا السكوات. من غير مسرح عصائر.',
        hoursTitle: 'المواعيد',
        hours: 'سبت–خميس ٦ ص–١١ م · جمعة ٨–٨ م',
        bookTitle: 'احجز تجربة',
        bookBody: 'كلاس مجاني واحد. البس جزمة ترفع فيها.',
        name: 'الاسم',
        phone: 'الموبايل',
        date: 'التاريخ',
        slot: 'الكلاس',
        submit: 'تأكيد التجربة',
        success: 'التجربة اتحجزت. ده ديمو — مفيش كلاس حقيقي.',
        slots: ['٦:٣٠ رفع', '٩:٠٠ كوند', '١٢:٠٠ رفع', '٦:٣٠ م', '٨:٠٠ مفتوح'],
        chat: {
          open: 'فتح الدردشة',
          close: 'إغلاق الدردشة',
          title: 'فورج',
          subtitle: 'بوت الأسئلة · على الصفحة',
          placeholder: 'تجربة، مواعيد، كلاسات…',
          send: 'إرسال',
          hello: 'اسأل عن التجربة أو المواعيد أو تجيب إيه.',
          fallback: 'بجاوب أسئلة الجيم هنا. للحجز استخدم احجز تجربة.',
          suggestions: ['التجربة مجانية؟', 'المواعيد؟', 'أجيب إيه؟'],
          faq: [
            { keys: ['تجربة', 'مجاني', 'أول', 'فري'], a: 'نعم. كلاس مجاني واحد. احجز تجربة على الصفحة. الكوتش يظبط المستوى.' },
            { keys: ['ميعاد', 'ساعة', 'فاتح'], a: 'سبت–خميس ٦ ص–١١ م. الجمعة ٨ ص–٨ م.' },
            { keys: ['أجيب', 'لبس', 'جزمة'], a: 'جزمة فلات، مية، فوطة. عندنا طباشير. من غير بيرفيوم على الأرض.' },
            { keys: ['حجز', 'كلاس', 'موعد'], a: 'استخدم احجز تجربة على الصفحة. اختار وقت الكلاس.' },
            { keys: ['سعر', 'اشتراك', 'كام'], a: 'الاشتراك يتقال بعد التجربة في الجيم. البوت مش بياخد فلوس.' },
          ],
        },
      },
    },
  },
  {
    id: 'agency',
    url: 'noonstudio.demo',
    img: '/demos/agency.png',
    accent: '#E0A84A',
    bg: '#141210',
    fg: '#F3EDE4',
    muted: '#A89B8C',
    copy: {
      en: {
        brand: 'Noon Studio',
        kind: 'Agency',
        headline: 'Brand work. Book the hour.',
        sub: 'A small studio. Discovery calls, not a contact form that disappears.',
        navBook: 'Book a call',
        cta: 'Book a discovery call',
        aboutTitle: 'The studio',
        about: 'Identity, sites, and campaigns for teams who already know what they sell. We start with a 40-minute desk hour.',
        hoursTitle: 'Hours',
        hours: 'Sun–Thu 10:00–18:00',
        bookTitle: 'Book a discovery call',
        bookBody: 'Forty minutes. Camera on. Bring the current site and what is broken.',
        name: 'Name',
        phone: 'Phone',
        date: 'Date',
        slot: 'Time',
        submit: 'Book the hour',
        success: 'Call held. This is a demo — no real meeting was booked.',
        slots: ['10:00', '11:30', '13:00', '15:00', '16:30'],
        chat: {
          open: 'Open chat',
          close: 'Close chat',
          title: 'Noon',
          subtitle: 'FAQ bot · on this page',
          placeholder: 'Calls, timing, what you do…',
          send: 'Send',
          hello: 'Ask how booking works, or what the studio does.',
          fallback: 'I only answer studio FAQs here. Use Book a call for a slot.',
          suggestions: ['How do I book?', 'What do you do?', 'How long is the call?'],
          faq: [
            { keys: ['book', 'call', 'appoint', 'slot'], a: 'Use Book a discovery call on this page. Forty minutes. We send a calendar note after you submit.' },
            { keys: ['do you', 'service', 'work', 'what'], a: 'Brand identity, campaign sites, and launch work. Not social media retainers.' },
            { keys: ['long', 'minute', 'duration', 'hour'], a: 'The first meeting is 40 minutes. No deck. Bring the live URL.' },
            { keys: ['price', 'cost', 'quote'], a: 'We quote after the call. The bot does not send prices.' },
            { keys: ['where', 'cairo', 'office'], a: 'Garden City studio, by appointment only.' },
          ],
        },
      },
      ar: {
        brand: 'نون ستوديو',
        kind: 'وكالة',
        headline: 'شغل براند. احجز الساعة.',
        sub: 'ستوديو صغير. مكالمة تعارف، مش فورم بيختفي.',
        navBook: 'احجز مكالمة',
        cta: 'احجز مكالمة تعارف',
        aboutTitle: 'الاستوديو',
        about: 'هوية ومواقع وحملات لفرق عارفة بتبيع إيه. نبدأ بساعة مكتب ٤٠ دقيقة.',
        hoursTitle: 'المواعيد',
        hours: 'أحد–خميس ١٠ ص–٦ م',
        bookTitle: 'احجز مكالمة تعارف',
        bookBody: 'أربعين دقيقة. الكاميرا مفتوحة. هات الموقع الحالي وإيه المكسور.',
        name: 'الاسم',
        phone: 'الموبايل',
        date: 'التاريخ',
        slot: 'الوقت',
        submit: 'حجز الساعة',
        success: 'المكالمة اتحجزت. ده ديمو — مفيش ميتنج حقيقي.',
        slots: ['١٠:٠٠', '١١:٣٠', '١٣:٠٠', '١٥:٠٠', '١٦:٣٠'],
        chat: {
          open: 'فتح الدردشة',
          close: 'إغلاق الدردشة',
          title: 'نون',
          subtitle: 'بوت الأسئلة · على الصفحة',
          placeholder: 'حجز، وقت، بتقدموا إيه…',
          send: 'إرسال',
          hello: 'اسأل عن الحجز أو شغل الاستوديو.',
          fallback: 'بجاوب أسئلة الاستوديو هنا. للحجز استخدم احجز مكالمة.',
          suggestions: ['أحجز إزاي؟', 'بتعملوا إيه؟', 'المكالمة كام دقيقة؟'],
          faq: [
            { keys: ['حجز', 'مكالمة', 'موعد'], a: 'استخدم احجز مكالمة تعارف على الصفحة. ٤٠ دقيقة. بعد الإرسال نبعت نوت في التقويم.' },
            { keys: ['شغل', 'خدمة', 'تعمل'], a: 'هوية براند ومواقع حملات وشغل إطلاق. مش سوشيال ميديا ريتينر.' },
            { keys: ['دقيق', 'مدة', 'ساعة', 'طول'], a: 'أول اجتماع ٤٠ دقيقة. من غير ديك. هات الرابط الحي.' },
            { keys: ['سعر', 'تكلفة', 'كام'], a: 'نسعّر بعد المكالمة. البوت مش بيبعت أسعار.' },
            { keys: ['فين', 'مكتب', 'قاهرة'], a: 'ستوديو جاردن سيتي، بموعد فقط.' },
          ],
        },
      },
    },
  },
]

export function demoById(id: string | undefined): Demo | undefined {
  return DEMOS.find(d => d.id === id)
}
