import type { Locale } from '../i18n/translations'
import type { DemoId } from './data'

export type SiteCard = { title: string; body: string; meta: string }
export type SiteFaq = { q: string; a: string }

export type SiteCopy = {
  ribbon: string
  want: string
  wantWa: string
  location: string
  locationHint: string
  navAbout: string
  navHours: string
  cardsTitle: string
  cards: SiteCard[]
  faqsTitle: string
  faqs: SiteFaq[]
  order: string
  orderDone: string
  prefer: string
  prefers: string[]
  payTitle: string
  payOptions: string[]
  payCta: string
  payDone: string
  mapLabel: string
  footerNote: string
  guests?: string
  guestCounts?: string[]
}

export const siteCopy: Record<DemoId, Record<Locale, SiteCopy>> = {
  cafe: {
    en: {
      ribbon: 'Demo 01 · AutoLeadss Studio · tasting pass and a barista FAQ on the page',
      want: 'Want a site like this?',
      wantWa: 'I saw the Qahwa House Road 9 demo on AutoLeadss. I want a cafe site with table booking and a FAQ chatbot.',
      location: 'Road 9, Maadi',
      locationHint: 'Three minutes from Degla Metro. Valet assisted.',
      navAbout: 'The house',
      navHours: 'Hours',
      cardsTitle: 'Single-origin roasts',
      cards: [
        { title: 'Yirgacheffe washed', body: 'Light, floral, better in a V60 than a machine.', meta: '380 EGP' },
        { title: 'Pink Bourbon anaerobic', body: 'Huila micro-lot. Blood orange and wild honey.', meta: '420 EGP' },
        { title: 'Cold drip elixir', body: 'Yemen Haraz, 42 hours in the tower. 500ml glass.', meta: '260 EGP' },
        { title: 'Cardamom date brioche', body: 'From the oven twice a day. Siwa date caramel.', meta: '110 EGP' },
      ],
      faqsTitle: 'Before you come',
      faqs: [
        { q: 'Can you grind for V60?', a: 'Yes. EK43 daily for V60, Aeropress, French press, and ibrik.' },
        { q: 'How fresh is the roast?', a: 'Within 48 hours, nitrogen tins, batch on the bottom.' },
        { q: 'Delivery in Cairo?', a: 'Same-day Maadi if you order by 2 PM. Next morning for Zamalek and New Cairo.' },
        { q: 'Can I work in the library?', a: 'Yes. Power, 150 Mbps, quiet room.' },
      ],
      order: 'Order (demo)',
      orderDone: 'Demo only — no order was sent.',
      prefer: 'Zone',
      prefers: ['Sunken garden', 'Roaster counter', 'AC library'],
      payTitle: '',
      payOptions: [],
      payCta: '',
      payDone: '',
      mapLabel: 'Road 9 · Maadi',
      footerNote: 'Daily 7:30 AM–11:30 PM. We hold a table 15 minutes.',
      guests: 'Guests',
      guestCounts: ['1', '2', '3', '4'],
    },
    ar: {
      ribbon: 'ديمو ٠١ · استوديو أوتوليدز · باس تذوق وشات بوت على الصفحة',
      want: 'عايز موقع شبه كده؟',
      wantWa: 'شفت ديمو قهوة هاوس شارع ٩ على AutoLeadss. عايز موقع مقهى بحجز ترابيزة وشات بوت.',
      location: 'شارع ٩، المعادي',
      locationHint: '٣ دقايق من مترو دجلة. فاليه.',
      navAbout: 'البيت',
      navHours: 'المواعيد',
      cardsTitle: 'تحميص أصول مفردة',
      cards: [
        { title: 'يرقا تشيف مغسول', body: 'فاتح وزهري. أحسن في V60 من الماكينة.', meta: '٣٨٠ جنيه' },
        { title: 'بينك بوربون لاهوائي', body: 'مايكرو-لوت ويلا. برتقال دم وعسل بري.', meta: '٤٢٠ جنيه' },
        { title: 'إكسير كولد دريب', body: 'يمن حراز، ٤٢ ساعة في التاور. ٥٠٠ مل.', meta: '٢٦٠ جنيه' },
        { title: 'بريوش هيل وعجوة', body: 'من الفرن مرتين في اليوم. كراميل سيوة.', meta: '١١٠ جنيه' },
      ],
      faqsTitle: 'قبل ما تيجي',
      faqs: [
        { q: 'بتحنوا لـ V60؟', a: 'نعم. EK43 يومياً لـ V60 والأيروبريس والفرنش والإبريق.' },
        { q: 'التحميص طازج قد إيه؟', a: 'خلال ٤٨ ساعة، علب نيتروجين، رقم الدفعة تحت.' },
        { q: 'توصيل القاهرة؟', a: 'نفس اليوم المعادي لو الطلب قبل ٢. تاني يوم الزمالك والقاهرة الجديدة.' },
        { q: 'أشتغل في المكتبة؟', a: 'نعم. باور وفايبر ١٥٠ وأوضة هادية.' },
      ],
      order: 'اطلب (ديمو)',
      orderDone: 'ده ديمو — مفيش طلب اتبعت.',
      prefer: 'الزون',
      prefers: ['الجاردن الغاطس', 'كاونتر المحمصة', 'مكتبة التكييف'],
      payTitle: '',
      payOptions: [],
      payCta: '',
      payDone: '',
      mapLabel: 'شارع ٩ · المعادي',
      footerNote: 'يومياً ٧:٣٠ ص–١١:٣٠ م. نمسك الترابيزة ربع ساعة.',
      guests: 'عدد الناس',
      guestCounts: ['١', '٢', '٣', '٤'],
    },
  },
  dentist: {
    en: {
      ribbon: 'Demo site · visit booking and a FAQ bot on the page',
      want: 'Want a site like this?',
      wantWa: 'I saw the Nile Dental demo on AutoLeadss. I want a clinic site with appointment booking and a FAQ chatbot.',
      location: 'New Cairo',
      locationHint: 'Quiet practice. We explain before we touch anything.',
      navAbout: 'The clinic',
      navHours: 'Hours',
      cardsTitle: 'What the first visits cover',
      cards: [
        { title: 'New patient exam', body: 'We look, we explain, we plan. No pressure to start treatment that day.', meta: '40 min' },
        { title: 'Hygiene', body: 'Scale and polish. You leave knowing what to do at home.', meta: '45 min' },
        { title: 'Whitening', body: 'In-chair, after a checkup, if the enamel is ready.', meta: 'After exam' },
        { title: 'Filling', body: 'After the exam and a clear plan. Not on the first visit unless you ask.', meta: 'By plan' },
      ],
      faqsTitle: 'First-visit questions',
      faqs: [
        { q: 'Will you start treatment on day one?', a: 'Not unless you ask. The first visit is 40 minutes: look, explain, plan.' },
        { q: 'Do you whiten?', a: 'Yes, after a checkup. We will say no if the enamel is not ready.' },
        { q: 'Friday?', a: 'Closed Friday. Saturday 11:00–16:00. Sun–Thu 10:00–20:00.' },
        { q: 'Pain the same day?', a: 'Use Book a visit and pick the next open slot. This demo has no clinic phone.' },
      ],
      order: '',
      orderDone: '',
      prefer: 'Time of day',
      prefers: ['Either', 'Morning', 'Evening'],
      payTitle: '',
      payOptions: [],
      payCta: '',
      payDone: '',
      mapLabel: 'New Cairo',
      footerNote: 'We call the day before. Closed Friday.',
    },
    ar: {
      ribbon: 'موقع تجريبي · حجز زيارة وشات بوت على الصفحة',
      want: 'عايز موقع شبه كده؟',
      wantWa: 'شفت ديمو نايل دينتال على AutoLeadss. عايز موقع عيادة بحجز مواعيد وشات بوت.',
      location: 'القاهرة الجديدة',
      locationHint: 'عيادة هادية. نشرح قبل ما نلمس حاجة.',
      navAbout: 'العيادة',
      navHours: 'المواعيد',
      cardsTitle: 'أول الزيارات بتشمل إيه',
      cards: [
        { title: 'كشف مريض جديد', body: 'نبص ونشرح ونخطط. من غير ضغط تبدأ علاج يومها.', meta: '٤٠ دقيقة' },
        { title: 'تنظيف', body: 'تقليح وتلميع. تمشي عارف تعمل إيه في البيت.', meta: '٤٥ دقيقة' },
        { title: 'تبييض', body: 'في العيادة بعد كشف، لو المينا جاهزة.', meta: 'بعد الكشف' },
        { title: 'حشو', body: 'بعد الكشف وخطة واضحة. مش أول زيارة إلا لو طلبت.', meta: 'حسب الخطة' },
      ],
      faqsTitle: 'أسئلة أول زيارة',
      faqs: [
        { q: 'هتبدأوا علاج أول يوم؟', a: 'لأ إلا لو طلبت. أول زيارة ٤٠ دقيقة: نبص ونشرح ونخطط.' },
        { q: 'بتبيضوا؟', a: 'نعم، بعد كشف. هنقول لأ لو المينا مش جاهزة.' },
        { q: 'الجمعة؟', a: 'الجمعة مغلق. السبت ١١–٤. الأحد–الخميس ١٠–٨ م.' },
        { q: 'وجع في نفس اليوم؟', a: 'استخدم احجز زيارة واختار أقرب موعد. الديمو مفيهوش تليفون عيادة.' },
      ],
      order: '',
      orderDone: '',
      prefer: 'وقت اليوم',
      prefers: ['أي وقت', 'صباح', 'مساء'],
      payTitle: '',
      payOptions: [],
      payCta: '',
      payDone: '',
      mapLabel: 'القاهرة الجديدة',
      footerNote: 'نتصل قبلها بيوم. الجمعة مغلق.',
    },
  },
  gym: {
    en: {
      ribbon: 'Demo site · trial booking and a FAQ bot on the page',
      want: 'Want a site like this?',
      wantWa: 'I saw the Forge gym demo on AutoLeadss. I want a gym site with class booking and a FAQ chatbot.',
      location: 'Warehouse floor',
      locationHint: 'Barbells, a 6am class, coaches who watch the back squat.',
      navAbout: 'The floor',
      navHours: 'Hours',
      cardsTitle: 'How you pay after the trial',
      cards: [
        { title: 'Trial class', body: 'One session. The coach scales it. Wear shoes you can lift in.', meta: 'Free' },
        { title: 'Drop-in', body: 'After you have been once. Cash or a transfer at the desk.', meta: '250 EGP' },
        { title: 'Open floor', body: 'After 18:00. Members and drop-ins. No class programming.', meta: 'From 18:00' },
      ],
      faqsTitle: 'Before you lift',
      faqs: [
        { q: 'Is the trial free?', a: 'Yes. One class. Book it on this page.' },
        { q: 'What do I bring?', a: 'Flat shoes, water, a towel. We have chalk. No perfume on the floor.' },
        { q: 'Membership price?', a: 'Quoted in person after the trial. The bot does not take payment.' },
        { q: 'Friday hours?', a: 'Friday 8:00–20:00. Other days 6:00–23:00.' },
      ],
      order: '',
      orderDone: '',
      prefer: 'Class',
      prefers: [],
      payTitle: 'Drop-in (demo)',
      payOptions: ['InstaPay', 'Vodafone Cash', 'Cash at desk'],
      payCta: 'Mark paid',
      payDone: 'Demo only — nothing was charged.',
      mapLabel: 'Cairo',
      footerNote: 'No juice bar. Chalk on the shelf.',
    },
    ar: {
      ribbon: 'موقع تجريبي · حجز تجربة وشات بوت على الصفحة',
      want: 'عايز موقع شبه كده؟',
      wantWa: 'شفت ديمو جيم فورج على AutoLeadss. عايز موقع جيم بحجز كلاسات وشات بوت.',
      location: 'أرض المخزن',
      locationHint: 'باربلز وكلاس ٦ الصبح وكوتشز بيراقبوا السكوات.',
      navAbout: 'الأرض',
      navHours: 'المواعيد',
      cardsTitle: 'الدفع بعد التجربة',
      cards: [
        { title: 'كلاس تجريبي', body: 'جلسة واحدة. الكوتش يظبط المستوى. البس جزمة ترفع فيها.', meta: 'مجاني' },
        { title: 'دخول يوم', body: 'بعد ما تيجي مرة. كاش أو تحويل عند الديسك.', meta: '٢٥٠ جنيه' },
        { title: 'أرض مفتوحة', body: 'بعد ٦ م. للأعضاء ودخول اليوم. من غير برنامج كلاس.', meta: 'من ٦ م' },
      ],
      faqsTitle: 'قبل ما ترفع',
      faqs: [
        { q: 'التجربة مجانية؟', a: 'نعم. كلاس واحد. احجزه من الصفحة.' },
        { q: 'أجيب إيه؟', a: 'جزمة فلات، مية، فوطة. عندنا طباشير. من غير بيرفيوم على الأرض.' },
        { q: 'سعر الاشتراك؟', a: 'يتقال بعد التجربة في الجيم. البوت مش بياخد فلوس.' },
        { q: 'الجمعة؟', a: 'الجمعة ٨ ص–٨ م. باقي الأيام ٦ ص–١١ م.' },
      ],
      order: '',
      orderDone: '',
      prefer: 'الكلاس',
      prefers: [],
      payTitle: 'دخول يوم (ديمو)',
      payOptions: ['إنستاباي', 'فودافون كاش', 'كاش عند الديسك'],
      payCta: 'تم الدفع',
      payDone: 'ده ديمو — مفيش حاجة اتخصمت.',
      mapLabel: 'القاهرة',
      footerNote: 'من غير عصائر. الطباشير على الرف.',
    },
  },
  agency: {
    en: {
      ribbon: 'Demo site · call booking and a FAQ bot on the page',
      want: 'Want a site like this?',
      wantWa: 'I saw the Noon Studio demo on AutoLeadss. I want a studio site with appointment booking and a FAQ chatbot.',
      location: 'Garden City, by appointment',
      locationHint: 'Identity, sites, and launch work. Not a social retainer.',
      navAbout: 'The studio',
      navHours: 'Hours',
      cardsTitle: 'Selected work (demo)',
      cards: [
        { title: 'Shop identity', body: 'A mark and a short name for a Downtown shop.', meta: 'Cairo' },
        { title: 'Clinic website', body: 'A quiet site with booking on the page.', meta: 'New Cairo' },
        { title: 'Cafe launch', body: 'Menu, hours, and a table form — the brief for a room like Qahwa.', meta: 'Maadi' },
      ],
      faqsTitle: 'How the hour works',
      faqs: [
        { q: 'How long is the call?', a: 'Forty minutes. Camera on. Bring the live URL and what is broken.' },
        { q: 'Do you quote on this page?', a: 'No. We quote after the call. The bot does not send prices.' },
        { q: 'Where is the studio?', a: 'Garden City, by appointment only.' },
        { q: 'Social media retainers?', a: 'No. Identity, campaign sites, and launch work.' },
      ],
      order: '',
      orderDone: '',
      prefer: 'Call type',
      prefers: ['Site', 'Identity', 'Both'],
      payTitle: '',
      payOptions: [],
      payCta: '',
      payDone: '',
      mapLabel: 'Garden City',
      footerNote: 'Sun–Thu 10:00–18:00. Desk hour is 40 minutes.',
    },
    ar: {
      ribbon: 'موقع تجريبي · حجز مكالمة وشات بوت على الصفحة',
      want: 'عايز موقع شبه كده؟',
      wantWa: 'شفت ديمو نون ستوديو على AutoLeadss. عايز موقع ستوديو بحجز مواعيد وشات بوت.',
      location: 'جاردن سيتي، بموعد',
      locationHint: 'هوية ومواقع وشغل إطلاق. مش سوشيال ريتينر.',
      navAbout: 'الاستوديو',
      navHours: 'المواعيد',
      cardsTitle: 'شغل مختار (ديمو)',
      cards: [
        { title: 'هوية محل', body: 'علامة واسم قصير لمحل في وسط البلد.', meta: 'القاهرة' },
        { title: 'موقع عيادة', body: 'موقع هادي وحجز على الصفحة.', meta: 'القاهرة الجديدة' },
        { title: 'إطلاق مقهى', body: 'منيو ومواعيد وفورم ترابيزة — نفس فكرة قهوة.', meta: 'الزمالك' },
      ],
      faqsTitle: 'الساعة بتتم إزاي',
      faqs: [
        { q: 'المكالمة كام دقيقة؟', a: 'أربعين. الكاميرا مفتوحة. هات الرابط الحي وإيه المكسور.' },
        { q: 'بتسعروا من الصفحة؟', a: 'لأ. نسعّر بعد المكالمة. البوت مش بيبعت أسعار.' },
        { q: 'الاستوديو فين؟', a: 'جاردن سيتي، بموعد فقط.' },
        { q: 'سوشيال ميديا ريتينر؟', a: 'لأ. هوية ومواقع حملات وشغل إطلاق.' },
      ],
      order: '',
      orderDone: '',
      prefer: 'نوع المكالمة',
      prefers: ['موقع', 'هوية', 'الاتنين'],
      payTitle: '',
      payOptions: [],
      payCta: '',
      payDone: '',
      mapLabel: 'جاردن سيتي',
      footerNote: 'أحد–خميس ١٠–٦. ساعة المكتب ٤٠ دقيقة.',
    },
  },
  lashes: {
    en: {
      ribbon: 'Demo site · lash-set booking and a FAQ bot on the page',
      want: 'Want a site like this?',
      wantWa: 'I saw the Lash Cartel demo on AutoLeadss. I want a studio site with appointment booking and a FAQ chatbot.',
      location: 'Zamalek, off 26th of July',
      locationHint: 'Quiet room. Street parking on the corniche side. No walk-ins after 18:00.',
      navAbout: 'The sets',
      navHours: 'Hours',
      cardsTitle: 'The sets',
      cards: [
        { title: 'Classic', body: 'One extension per natural lash. Clean line, about 90 minutes.', meta: '1,200 EGP' },
        { title: 'Volume', body: 'Handmade fans. Softer density. Two hours on the bed.', meta: '1,800 EGP' },
        { title: 'Hybrid', body: 'Classic mixed with fans. The usual first set here.', meta: '1,500 EGP' },
        { title: 'Fill', body: 'Two to three weeks after a full set. About 75 minutes.', meta: '850 EGP' },
      ],
      faqsTitle: 'Before you book',
      faqs: [
        { q: 'Classic or volume?', a: 'Classic is one-to-one. Volume is fans. Hybrid mixes both. Pick it on the form.' },
        { q: 'Do I need a patch test?', a: 'New clients: 48 hours before. Tell us if your eyes run.' },
        { q: 'How soon is a fill?', a: 'Two to three weeks. Book a fill slot on this page.' },
        { q: 'Walk-ins?', a: 'Not after 18:00. Use Book a set.' },
      ],
      order: '',
      orderDone: '',
      prefer: 'The set',
      prefers: ['Classic', 'Volume', 'Hybrid', 'Fill'],
      payTitle: '',
      payOptions: [],
      payCta: '',
      payDone: '',
      mapLabel: 'Zamalek · Cairo',
      footerNote: 'Sat–Thu 10:00–20:00. We hold the bed 15 minutes.',
    },
    ar: {
      ribbon: 'موقع تجريبي · حجز ست رموش وشات بوت على الصفحة',
      want: 'عايز موقع شبه كده؟',
      wantWa: 'شفت ديمو لاش كارتل على AutoLeadss. عايز موقع استوديو بحجز مواعيد وشات بوت.',
      location: 'الزمالك، جنب ٢٦ يوليو',
      locationHint: 'أوضة هادية. ركن ناحية الكورنيش. من غير دخول من غير معاد بعد ٦.',
      navAbout: 'الستات',
      navHours: 'المواعيد',
      cardsTitle: 'الستات',
      cards: [
        { title: 'كلاسيك', body: 'رمش لرمش. خط نضيف، حوالي ٩٠ دقيقة.', meta: '١٬٢٠٠ جنيه' },
        { title: 'فوليوم', body: 'فانز يدوي. كثافة أنعم. ساعتين على السرير.', meta: '١٬٨٠٠ جنيه' },
        { title: 'هايبريد', body: 'كلاسيك مع فانز. أول ست المعتاد هنا.', meta: '١٬٥٠٠ جنيه' },
        { title: 'فيل', body: 'بعد أسبوعين–تلاتة من الست الكامل. حوالي ٧٥ دقيقة.', meta: '٨٥٠ جنيه' },
      ],
      faqsTitle: 'قبل الحجز',
      faqs: [
        { q: 'كلاسيك ولا فوليوم؟', a: 'الكلاسيك واحد لواحد. الفوليوم فانز. الهايبريد الاتنين. اختار من الفورم.' },
        { q: 'محتاج اختبار لزق؟', a: 'عملاء جدد: قبلها بـ ٤٨ ساعة. قوليلنا لو عينك بتدمع.' },
        { q: 'الفيل امتى؟', a: 'أسبوعين–تلاتة. احجز فيل من الصفحة.' },
        { q: 'من غير معاد؟', a: 'لأ بعد ٦. استخدم احجز ست.' },
      ],
      order: '',
      orderDone: '',
      prefer: 'الست',
      prefers: ['كلاسيك', 'فوليوم', 'هايبريد', 'فيل'],
      payTitle: '',
      payOptions: [],
      payCta: '',
      payDone: '',
      mapLabel: 'الزمالك · القاهرة',
      footerNote: 'سبت–خميس ١٠–٨. نمسك السرير ربع ساعة.',
    },
  },
}
